// Generated by `promptframe dev`. Do not edit manually.
export type PromptFrameDevPublicResource = {
  publicPath: string;
  sourcePath: string;
  artifactPath: string;
  kind: string;
  contentType: string;
  sizeBytes: number;
  sha256: string;
};

export const promptFrameDevPublicResources: readonly PromptFrameDevPublicResource[] = [];
