// Generated by `promptframe dev`. Do not edit manually.
import type { ComponentPublicResourceKind } from '@promptframe/contracts';

export type PromptFrameDevPublicResource = {
  publicPath: string;
  sourcePath: string;
  artifactPath: string;
  kind: ComponentPublicResourceKind;
  contentType: string;
  sizeBytes: number;
  sha256: string;
};

export const promptFrameDevPublicResources: readonly PromptFrameDevPublicResource[] = [];
